### ISSUE TITLE
Beta - Permission and minus

### ISSUE THREAD

**Issue by Raffaele74** [carat-project/carat-android#26]
Finishing

**Comment by Raffaele74** [comment]
Just opened, Carat immediately sends you to the "App with access access" page without notice or explanation. Very hurst.

I'd like to find the build (now v2.17.6) in settings.

"Disable charging measurement" is not clear enough for me. I suppose it means I do not measure during the charge, but I do not understand why I should do it.

Signal thresholds are inverted (already reported) "<" vs ">".

The four buttons (Bugs Hogs WW Action) on the home page could not become a swipe window from the bottom?

![j1](https://user-images.githubusercontent.com/24221053/27822625-90e9fe50-60a6-11e7-8387-061f4ff4a3de.png)

**Comment by Raffaele74** [comment]
TOP 200 HOGS

They are 72. Out of 72, 50 have less them 1h.

I searched "Battery" in Top Hogs. Usual it showed me 4-5 apps with a lot of battery drain.
Now it shows me only  69 GSam Battery Monitor - only 5 minutes.

**Comment by Raffaele74** [comment]
Duplicate.

![screenshot_2017-07-04-16-08-08](https://user-images.githubusercontent.com/24221053/27833474-5340a6bc-60d3-11e7-9481-7548f2b3293d.png)

**Comment by lagerspetz** [comment]
You have put multiple issues in this same thread.
It's better to keep them separate.

1. Carat asks about access to usage stats, since that is needed on new Android models to get any idea what apps are running. There should be an explanation, but it might be in English.

2. We have changed the Carat analysis to only take the last year into account. This means normal behavior is more on par with current phones, and there are less obvious hogs. 
You can clearly see this on Carat statistics in the hog bubble chart:
http://carat.cs.helsinki.fi/statistics/

Before:
![before](https://user-images.githubusercontent.com/1171264/27834328-37b8be96-60df-11e7-96e7-21623b337efd.png)

After:
![after](https://user-images.githubusercontent.com/1171264/27834338-3e86e70c-60df-11e7-84b1-87701141c473.png)

3. The error / precision is mentioned also separately on purpose. Not everyone is familar with the -+ notation.

**Comment by Raffaele74** [comment]
Ok. I close this and open news. I also was not clear.
