### ISSUE TITLE
Top bugs

### ISSUE THREAD

**Issue by Raffaele74** [carat-project/carat-android#35]
In alfa Hogs are "used every time, in beta are "used last time", right? 
So a lot of ex hogs now become bugs. Better!
A top bugs may be nice, if easy.

**Comment by Raffaele74** [comment]
I'm happy to find "Battery savers".
I'm hod on to view in Top Hogs KasperSky Battery Life: bad copy of Carat !

**Comment by lagerspetz** [comment]
Top bugs is a bit difficult, because bugs are personal to each user. So, we need to decide things like:
-How many users should have a bug before it is shown?
-Are Top Bugs based on the number of users, or the amount battery drain?
-If a user already has a very low J-Score, his bugs may be of very low impact, but a user that rarely uses their phone, but has a very heavy app that he uses often, will probably see a much higher impact bug. This needs to be taken into account somehow.

**Comment by Raffaele74** [comment]
Ok. I wrote this when we had few top hogs.
Now is not.
I close it.
